version: '3'

services:
  mysql-app:
    image: mysql
    container_name: mysql-app
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - dockerDemoNetwork

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-app
    ports:
      - 8082:80
    environment:
      - PMA_HOST=mysql-app
    networks:
      - dockerDemoNetwork
      
networks:
  dockerDemoNetwork:

