version: '3'

services:
  symfony-app:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: symfony-app:1.0
    container_name: symfony-app
    ports:
      - 8083:8080
    working_dir: /var/www
    depends_on:
      - mysql-app
    networks:
      - dockerDemoNetwork
      
  mysql-app:
    image: mysql
    container_name: mysql-app
    # ports:
    #   - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: dockerDemoDB
      MYSQL_USER: docker
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - dockerDemoNetwork
    volumes:
      - symfony-app-volumes:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-app
    ports:
      - 8082:80
    environment:
      - PMA_HOST=mysql-app
    networks:
      - dockerDemoNetwork
      
networks:
  dockerDemoNetwork:

volumes:
  symfony-app-volumes:
    driver: local
